version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product_review_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      app-network:
        aliases:
          - postgres-db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: product-review-backend
    restart: always
    ports:
      - "3001:3001"
      - "5556:5556"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres-db:5432/product_review_db
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/frontend-app
      dockerfile: Dockerfile.frontend
    container_name: product-review-frontend
    restart: always
    ports:
      - "3000:80"  # Exposes container port 80 as port 3000 on the host
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
