jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Backend steps with updated Node version
      - name: Set up Node for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18.18'
      - name: Install dependencies (backend)
        working-directory: backend
        run: npm install
      - name: Run tests (backend)
        working-directory: backend
        run: npm test

      # Frontend steps (if needed, update version similarly)
      - name: Set up Node for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18.18'  # or '18' if your frontend works fine with 18.x
      - name: Install dependencies (frontend)
        working-directory: frontend/frontend-app
        run: npm install
      - name: Run tests (frontend)
        working-directory: frontend/frontend-app
        run: npm test

      - name: Build Docker images
        run: docker-compose build

      - name: Log in to Docker Hub
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        run: docker-compose push
