name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Backend steps
      - name: Set up Node for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18.18'
      - name: Install dependencies (backend)
        working-directory: backend
        run: npm install
      - name: Run tests (backend)
        working-directory: backend
        run: npm test

      # Frontend steps
      - name: Set up Node for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18.18'
      - name: Install dependencies (frontend)
        working-directory: frontend/frontend-app
        run: npm install
      - name: Run tests (frontend)
        working-directory: frontend/frontend-app
        run: npm test

      # Debug: Check Docker Compose Version
      - name: Check Docker Compose Version
        run: docker compose version

      # Build Docker images using Docker Compose with no cache and plain progress output
      - name: Build Docker images
        run: docker compose build --no-cache --progress=plain

      # Log in to Docker Hub if credentials are provided
      - name: Log in to Docker Hub
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      # Push Docker images if credentials are provided
      - name: Push Docker images
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        run: docker compose push

      # Debug step to print Docker credentials (without exposing sensitive info)
      - name: Debug Docker Credentials
        run: |
          echo "Docker Username: $DOCKER_USERNAME"
          echo "Docker Password is set: $([ -n "$DOCKER_PASSWORD" ] && echo yes || echo no)"
